server:
  port: ${PORT:8080}   # ✅ 关键！

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # ✅ 改这里

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

  mail:
    host: smtp.qq.com
    port: 587
    username: 1187328981@qq.com
    password: tburkyggcpyijief
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: GameStore2024VeryLongSecretKeyForJWTSigningPurpose
  expiration: 86400000

logging:
  level:
    com.gamestore: DEBUG

email:
  code:
    expire: 300
